name: CI

env:
  ci: true

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-18.04, macos-11.0]

    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: Dist build
        run: |
          yarn dist
